// Brand Constants
export const BRAND_NAME = "SAYURA";

// Navigation Links
export const NAV_LINKS = [
  { label: "Collections", href: "/collections" },
  { label: "New Arrivals", href: "/new-arrivals" },
  { label: "Store Locator", href: "/stores" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

// Social Media Links
export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/sayura.in",
  facebook: "#",
  pinterest: "#",
};

// Product Categories
export const PRODUCT_CATEGORIES = [
  "All",
  "Dresses",
  "Sarees",
  "Sets",
  "Outerwear",
  "Accessories",
];

// Enhanced Product Data with Premium Features
export const SAMPLE_PRODUCTS = [
  {
    id: 1,
    name: "Silk Evening Dress",
    category: "Dresses",
    price: 12999,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg"],
    slug: "silk-evening-dress",
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    isLimited: false,
    colors: ["Champagne", "Midnight Blue"],
    tags: ["new", "featured", "evening-wear"],
    shortDescription: "Elegant silk dress perfect for sophisticated evenings",
    dateAdded: "2025-10-10",
  },
  {
    id: 2,
    name: "Embroidered Jacket",
    category: "Outerwear",
    price: 15999,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg"],
    slug: "embroidered-jacket",
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    isLimited: false,
    colors: ["Black", "Burgundy"],
    tags: ["new", "bestseller"],
    shortDescription: "Intricately embroidered jacket with traditional motifs",
    dateAdded: "2025-10-09",
  },
  {
    id: 3,
    name: "Cotton Palazzo Set",
    category: "Sets",
    price: 8999,
    image: "/images/products/product-3.jpg",
    images: ["/images/products/product-3.jpg"],
    slug: "cotton-palazzo-set",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: false,
    colors: ["Ivory", "Coral"],
    tags: ["new", "casual"],
    shortDescription: "Comfortable and stylish palazzo set for everyday elegance",
    dateAdded: "2025-10-08",
  },
  {
    id: 4,
    name: "Designer Saree",
    category: "Sarees",
    price: 18999,
    image: "/images/products/product-4.jpg",
    images: ["/images/products/product-4.jpg"],
    slug: "designer-saree",
    isNew: true,
    isFeatured: true,
    isBestSeller: true,
    isLimited: true,
    colors: ["Gold", "Emerald"],
    tags: ["new", "featured", "limited-edition", "bestseller"],
    shortDescription: "Exquisite designer saree with intricate embellishments",
    dateAdded: "2025-10-11",
  },
  {
    id: 5,
    name: "Floral Midi Dress",
    category: "Dresses",
    price: 11499,
    image: "/images/products/product-5.jpg",
    images: ["/images/products/product-5.jpg"],
    slug: "floral-midi-dress",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: false,
    colors: ["Rose", "Lavender"],
    tags: ["new", "spring-collection"],
    shortDescription: "Romantic floral midi dress for daytime elegance",
    dateAdded: "2025-10-07",
  },
  {
    id: 6,
    name: "Velvet Kurta Set",
    category: "Sets",
    price: 13499,
    image: "/images/products/product-6.jpg",
    images: ["/images/products/product-6.jpg"],
    slug: "velvet-kurta-set",
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    isLimited: false,
    colors: ["Navy", "Maroon"],
    tags: ["new", "bestseller", "festive"],
    shortDescription: "Luxurious velvet kurta set with elegant embroidery",
    dateAdded: "2025-10-06",
  },
  {
    id: 7,
    name: "Statement Cape Dress",
    category: "Dresses",
    price: 16999,
    image: "/images/products/product-7.jpg",
    images: ["/images/products/product-7.jpg"],
    slug: "statement-cape-dress",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: true,
    colors: ["Black", "Wine"],
    tags: ["new", "limited-edition", "evening-wear"],
    shortDescription: "Dramatic cape dress for unforgettable evenings",
    dateAdded: "2025-10-05",
  },
  {
    id: 8,
    name: "Silk Blend Saree",
    category: "Sarees",
    price: 14999,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg"],
    slug: "silk-blend-saree",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: false,
    colors: ["Royal Blue", "Teal"],
    tags: ["new", "traditional"],
    shortDescription: "Classic silk blend saree with modern sensibility",
    dateAdded: "2025-10-04",
  },
  {
    id: 9,
    name: "Embroidered Anarkali",
    category: "Dresses",
    price: 17499,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg"],
    slug: "embroidered-anarkali",
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    isLimited: false,
    colors: ["Mint", "Peach"],
    tags: ["new", "featured", "festive"],
    shortDescription: "Graceful anarkali with delicate embroidery",
    dateAdded: "2025-10-03",
  },
  {
    id: 10,
    name: "Contemporary Jacket",
    category: "Outerwear",
    price: 12999,
    image: "/images/products/product-10.jpg",
    images: ["/images/products/product-10.jpg"],
    slug: "contemporary-jacket",
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    isLimited: false,
    colors: ["Charcoal", "Beige"],
    tags: ["new", "bestseller", "casual"],
    shortDescription: "Modern jacket with clean lines and sophistication",
    dateAdded: "2025-10-02",
  },
  {
    id: 11,
    name: "Printed Palazzo Set",
    category: "Sets",
    price: 9999,
    image: "/images/products/product-11.jpg",
    images: ["/images/products/product-11.jpg"],
    slug: "printed-palazzo-set",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: false,
    colors: ["Multi", "Pastel"],
    tags: ["new", "summer-collection"],
    shortDescription: "Vibrant printed set for effortless summer style",
    dateAdded: "2025-10-01",
  },
  {
    id: 12,
    name: "Heritage Saree",
    category: "Sarees",
    price: 19999,
    image: "/images/products/product-12.jpg",
    images: ["/images/products/product-12.jpg"],
    slug: "heritage-saree",
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    isLimited: true,
    colors: ["Crimson", "Plum"],
    tags: ["new", "limited-edition", "heritage"],
    shortDescription: "Timeless heritage saree with authentic craftsmanship",
    dateAdded: "2025-09-30",
  },
  {
    id: 13,
    name: "Lace Evening Gown",
    category: "Dresses",
    price: 21999,
    image: "/images/products/product-13.jpg",
    images: ["/images/products/product-13.jpg"],
    slug: "lace-evening-gown",
    isNew: true,
    isFeatured: false,
    isBestSeller: true,
    isLimited: true,
    colors: ["Champagne", "Rose Gold"],
    tags: ["new", "bestseller", "limited-edition", "evening-wear"],
    shortDescription: "Ethereal lace gown for grand occasions",
    dateAdded: "2025-09-29",
  },
  {
    id: 14,
    name: "Structured Blazer",
    category: "Outerwear",
    price: 14499,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg"],
    slug: "structured-blazer",
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    isLimited: false,
    colors: ["Black", "Camel"],
    tags: ["bestseller", "workwear"],
    shortDescription: "Tailored blazer for powerful elegance",
    dateAdded: "2025-09-28",
  },
  {
    id: 15,
    name: "Draped Palazzo Set",
    category: "Sets",
    price: 10999,
    image: "/images/products/product-15.jpg",
    images: ["/images/products/product-15.jpg"],
    slug: "draped-palazzo-set",
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    isLimited: false,
    colors: ["Grey", "Dusty Pink"],
    tags: ["modern", "evening-wear"],
    shortDescription: "Elegantly draped set with contemporary flair",
    dateAdded: "2025-09-27",
  },
  {
    id: 16,
    name: "Cocktail Dress",
    category: "Dresses",
    price: 15499,
    image: "/images/products/product-16.jpg",
    images: ["/images/products/product-16.jpg"],
    slug: "cocktail-dress",
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    isLimited: false,
    colors: ["Black", "Emerald"],
    tags: ["bestseller", "party-wear"],
    shortDescription: "Chic cocktail dress for stylish celebrations",
    dateAdded: "2025-09-26",
  },
];

// Store Locations
export const STORE_LOCATIONS = [
  {
    id: 1,
    name: "SAYURA Mumbai Flagship",
    address: "123 Fashion Street, Bandra West, Mumbai, Maharashtra 400050",
    phone: "+91 22 1234 5678",
    hours: "10:00 AM - 9:00 PM",
    coordinates: { lat: 19.0596, lng: 72.8295 },
  },
  {
    id: 2,
    name: "SAYURA Delhi Store",
    address: "456 Khan Market, New Delhi, Delhi 110003",
    phone: "+91 11 1234 5678",
    hours: "10:00 AM - 8:30 PM",
    coordinates: { lat: 28.6139, lng: 77.2090 },
  },
  {
    id: 3,
    name: "SAYURA Bangalore Store",
    address: "789 MG Road, Bangalore, Karnataka 560001",
    phone: "+91 80 1234 5678",
    hours: "10:30 AM - 9:00 PM",
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },
];

// Collection Categories
export const COLLECTIONS = [
  {
    id: 1,
    title: "Spring Summer 2025",
    description: "Ethereal silhouettes meet contemporary design",
    image: "/images/collections/ss25.jpg",
    slug: "spring-summer-2025",
  },
  {
    id: 2,
    title: "Heritage Collection",
    description: "Timeless elegance with traditional craftsmanship",
    image: "/images/collections/heritage.jpg",
    slug: "heritage",
  },
  {
    id: 3,
    title: "Evening Luxe",
    description: "Sophisticated pieces for special occasions",
    image: "/images/collections/evening.jpg",
    slug: "evening-luxe",
  },
];

// Instagram Feed Placeholder (Replace with API data)
export const INSTAGRAM_POSTS = [
  { id: 1, image: "/images/instagram/post-1.jpg", url: SOCIAL_LINKS.instagram },
  { id: 2, image: "/images/instagram/post-2.jpg", url: SOCIAL_LINKS.instagram },
  { id: 3, image: "/images/instagram/post-3.jpg", url: SOCIAL_LINKS.instagram },
  { id: 4, image: "/images/instagram/post-4.jpg", url: SOCIAL_LINKS.instagram },
  { id: 5, image: "/images/instagram/post-5.jpg", url: SOCIAL_LINKS.instagram },
  { id: 6, image: "/images/instagram/post-6.jpg", url: SOCIAL_LINKS.instagram },
  { id: 7, image: "/images/instagram/post-7.jpg", url: SOCIAL_LINKS.instagram },
  { id: 8, image: "/images/instagram/post-8.jpg", url: SOCIAL_LINKS.instagram },
];
